### ISSUE TITLE
How to deal with multiple workers?

### ISSUE THREAD

**Issue by gardar** [Mecanik/cloudflare-image-resizing-worker#1]
First off I want to thank you for releasing the worker open source! I've been using the cloudflare-image-resizing plugin with great success but I'm excited to use a worker instead.

Can you give any guidance on how the worker script could co-exist with other workers?
I'm not super familiar with how the workers function, but I've already got [Edge Cache HTML via Cloudflare Workers](https://wordpress.org/plugins/edge-cache-html-cloudflare-workers/) enabled and if I try to add a wildcard route for the domain (`example.com/*`) I get the following error: `workers.api.error.duplicate_route`

**Comment by Mecanik** [comment]
I can help you, but I do not recommend using that plugin. It does more harm to your website than good.

HTML caching is not an easy task, it can be done for free, but not like that.

Please disable it, run my worker, see if all OK, then we get back to HTML caching.
