### ISSUE TITLE
Any way to exclude RSS Images and Social Sharing Images from Yoast?

### ISSUE THREAD

**Issue by swissky** [Mecanik/cloudflare-image-resizing-worker#10]
Hey, i love your worker. It works perfect. Just 2 wishes ;)

1. Maybe an LazyLoading Animation and that the first Image is not LazyLoaded
2. When i share my posts, there is no image. Same for RSS Feed. Thats not a problem normally, but with that worker.

**Comment by Mecanik** [comment]
Hello 👋,

Thanks, appreciate it.

1. There is already browser level lazy load, but indeed I should add a
feature to ignore some images.

2. This might be related to CSS or something like that, I really need to
see the issue to investigate it.

You can share some screenshots or even better URL.

**Comment by swissky** [comment]
Your welcome
I will send you the link on mail.
