### ISSUE TITLE
Seems to break sites

### ISSUE THREAD

**Issue by creativebastard** [Mecanik/cloudflare-image-resizing-worker#11]
Hey, awesome work on the worker, I've been using your plugin with great success! I'm having some issues when trying to use the worker, I can see that the worker is running, and verified on the CF side the logs are seeing requests, when I view the code on any of the pages on my site I can see the rewrite is happening, but it seems to break all images. I've enabled the worker, set the mode to production, made it run unbound, and then set the correct worker rules when to execute.

Any thoughts or ideas about what I might be doing wrong? As soon as I disable the worker, images load again with no problem.

**Comment by creativebastard** [comment]
Oh, and I disabled the plugin when I enabled the worker.

**Comment by Mecanik** [comment]
Hi,

You cannot use the worker and the plugin at the same time. I have added some exclusions in the latest version, but it's still not recommended.

Regards
