### ISSUE TITLE
Invalid Content Type: image/jpeg

### ISSUE THREAD

**Issue by berkmh** [Mecanik/cloudflare-image-resizing-worker#12]
getting this on all of my worker logs: 

"logs": [
    {
      "message": [
        "Invalid Content Type: image/jpeg"
      ],
      "level": "error",
      "timestamp": 1691289441837
    }

what could be wrong? 

also how does this work using a subdomain like your plugin? Im only using cloudflare for images using WP offload media to serve them...

**Comment by Mecanik** [comment]
Hi,

It seems the content type returned for the images is wrong. I cannot guess what's there and what kind of setup you have, but if you already "offloaded" your images into Cloudflare, image resizing makes no sense.

Please decide what you want to do and then take it step by step.

Regards
