### ISSUE TITLE
Maybe add some new functions

### ISSUE THREAD

**Issue by swissky** [Mecanik/cloudflare-image-resizing-worker#13]
Hey, did you saw this post here https://blog.cloudflare.com/speeding-up-your-website-in-a-few-clicks/
They added a Worker for better LCP, maybe something you can add to your Script ;) 

Best Kevin

**Comment by Mecanik** [comment]
Thanks, this is very easy to add. However it's an experimental feature, not sure how it behaves on other browsers.

**Comment by swissky** [comment]
Welcome back ;) And thank you. I`m still try to get the most out of Cloudflare Workers (something i`m still not understand 100%)

We will starting in the next weeks with CF Enterprise Plan for our clients. Looking now for all great Workers

**Comment by Mecanik** [comment]
Thanks, that's great to hear. I have had several clients now using the worker successfully. With the latest changes, you can run the worker for as many sites as you wish.

**Comment by swissky** [comment]
hmmm :-( https://blog.cloudflare.com/merging-images-and-image-resizing/

**Comment by Mecanik** [comment]
> hmmm :-( https://blog.cloudflare.com/merging-images-and-image-resizing/

I don't see this as a problem...
