### ISSUE TITLE
Multisite Support -> explain

### ISSUE THREAD

**Issue by swissky** [Mecanik/cloudflare-image-resizing-worker#14]
Hey, could you please explain to me the Multisite setup a little bit more. How a Setup would look for a site like this, where we use MultilingualPress, so each subsite is a language:

example.com/en
example.com/fr

The next question is about performance. I think the images need too much time to be visible. Sometimes just then when they are in the viewport. Yould you check if there is an "Preload critical images" supoort possible so leading images are not lazy loaded and then there is a Threshold for lazy loading images, so they are ready before they are visible?

Thank you

**Comment by Mecanik** [comment]
Hello,

This is not related to the "wp multisite" configuration. You can have:

```
example.com/en
example.com/fr
```

It makes no difference. What I mean by "multi site" is that you can setup one Worker and run many websites through it when you are using for example custom hostnames with an Enterprise account. Example:

Worker -> Triggers ->

```
example.com/* - Zone: another.com
example2.com/* - Zone: another.com
example3.com/* - Zone: another.com
```

You can also just use it normally for several websites / zones:

```
example.com/* - Zone: example.com
example2.com/* - Zone: example2.com
example3.com/* - Zone: example3.com
```

And so on. The idea is that you won't need to setup a worker for each website when you have many.

**Comment by swissky** [comment]
Okey thank you for the information. Then i have to check why the other pages don't have images. With your Plugin it worked the last 6 months, but now with Enterprise we want to move.
