### ISSUE TITLE
Some image thumbnails not going through image resize

### ISSUE THREAD

**Issue by creativebastard** [Mecanik/cloudflare-image-resizing-worker#17]
I'm having an issue with WooCommerce thumbnails not passing through the Cloudflare image resizing. It seems it may be an issue with the theme Salient we're using on a few sites. The image thumbnails have 140x140 appended to them. Happy to pay some $$ to get this fixed if need be.

**Comment by Mecanik** [comment]
Hi, happy to help but please get in touch via my [website](https://mecanik.dev/en/contact/) for this.
