### ISSUE TITLE
Corrupted image URLs

### ISSUE THREAD

**Issue by bravomediamats** [Mecanik/cloudflare-image-resizing-worker#21]
Hi!

Have been testing this, aswell as your plugin, but it does not work at all in my tests.

This is how the image links are rendered in the DOM:

https://{domain}/cdn-cgi/image/width=1536,height=1024,fit=crop,quality=90,gravity=auto,sharpen=1,metadata=none,format=auto,onerror=redirect/wp-content/uploads/2022/11/developers.jpg

And no images are visible.

Is this code still maintained? Saw a similar question in another issue, with no response.

**Comment by bravomediamats** [comment]
Nevermind, I had not activated image transform for the Zone in cloudflare. Working now.

**Comment by Mecanik** [comment]
I`m glad you sorted it.
