### ISSUE TITLE
Problems with Menus and Fonts

### ISSUE THREAD

**Issue by pauloshea42** [Mecanik/cloudflare-image-resizing-worker#3]
Hi Norbert,
Finally got a chance to try this out but seeing a couple of issues with fonts and menus. Maybe clashing with autoptimize? Some of the logs below:

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/json; charset=UTF-8"
      ],
      "level": "error",
      "timestamp": 1675895974501
    }
  ],
  "eventTimestamp": 1675895974327,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-json/contact-form-7/v1/contact-forms/138/feedback/schema",
      "method": "GET",
      "headers": {
        "accept": "application/json, */*;q=0.1",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>>>>>

{
  "outcome": "canceled",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Origin HTTP Status: 206"
      ],
      "level": "error",
      "timestamp": 1675895974291
    }
  ],
  "eventTimestamp": 1675895974282,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/kumoco.mp4",
      "method": "GET",
      "headers": {
        "accept": "video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/javascript; charset=UTF-8"
      ],
      "level": "error",
      "timestamp": 1675895973979
    }
  ],
  "eventTimestamp": 1675895973971,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-content/cache/autoptimize/js/autoptimize_1b6feac3c6e04cbeb13becdaeef2d0e4.js",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/javascript; charset=UTF-8"
      ],
      "level": "error",
      "timestamp": 1675895973983
    }
  ],
  "eventTimestamp": 1675895973963,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-includes/js/jquery/jquery.min.js",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/javascript; charset=UTF-8"
      ],
      "level": "error",
      "timestamp": 1675895973978
    }
  ],
  "eventTimestamp": 1675895973970,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-content/cache/autoptimize/js/autoptimize_single_1a8e0c5a2c777f63163809b92ff95004.js",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/octet-stream"
      ],
      "level": "error",
      "timestamp": 1675895973970
    }
  ],
  "eventTimestamp": 1675895973962,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-content/themes/kumoco/fonts/manrope/Manrope-VariableFont_wght.ttf",
      "method": "GET",
      "headers": {
        "accept": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

>>>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1675895973956,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-content/cache/autoptimize/css/autoptimize_081ee1e1b7acb8f875175d16d51e06ac.css",
      "method": "GET",
      "headers": {
        "accept": "text/css,*/*;q=0.1",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",
        "cf-connecting-ip": "80.4.133.158",
        "cf-ipcountry": "GB",
        "cf-ray": "7967dcad3bf57744",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "cookie": "REDACTED",
        "dnt": "1",
        "host": "staging.kumoco.com",
        "pragma": "no-cache",

>>>>>>>>>>>

{
  "outcome": "ok",
  "scriptName": "img",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Invalid Content Type: application/octet-stream"
      ],
      "level": "error",
      "timestamp": 1675895973970
    }
  ],
  "eventTimestamp": 1675895973962,
  "event": {
    "request": {
      "url": "https://staging.kumoco.com/wp-content/themes/kumoco/fonts/manrope/Manrope-VariableFont_wght.ttf",
      "method": "GET",
      "headers": {
        "accept": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cache-control": "no-cache",

**Comment by Mecanik** [comment]
Hi, sorry for the late reply. It may be the case yes, try and disable it for a quick test and see the result.
