### ISSUE TITLE
Images not resizing on mobile

### ISSUE THREAD

**Issue by nitaic** [Mecanik/cloudflare-image-resizing-worker#4]
Hi there,

Thank you for making this available for everyone.

I'm currently testing it on https://tinyurl.com/staging-site and it's working as expected on desktop. But on mobile the image urls are not being rewritten and so Cloudflare is not serving a resized image.

Any ideas why that might be?

**Comment by Mecanik** [comment]
Hi,

Investigate the Logs generated from the Worker in your Cloudflare dashboard. Also investigate the HTML output on mobile compare to desktop for images.

Thanks
