### ISSUE TITLE
It looks like it doesn't work with flatsome image slider

### ISSUE THREAD

**Issue by vss2023** [Mecanik/cloudflare-image-resizing-worker#5]
It looks like it doesn't work with flatsome image slider

https://vapesocietysupplies.com/products/glazed-donut-by-loaded-e-liquid-120ml/

**Comment by Mecanik** [comment]
Hi to you too.

And it does work:

![image](https://user-images.githubusercontent.com/12122357/230840728-495dcf9b-f7fc-4734-82d1-9a4c8d959d6e.png)

Example generated URL: https://vapesocietysupplies.com/cdn-cgi/image/width=405,height=304,/wp-content/uploads/2016/10/Glazed-Donuts-by-Loaded-E-Liquid-120ml-Back.jpg
