### ISSUE TITLE
Inline CSS overwritten by Worker

### ISSUE THREAD

**Issue by danmaby** [Mecanik/cloudflare-image-resizing-worker#6]
Hey Norbert, I've run into an issue with a site that's using the Kadence Block plugin. The plugin adds inline CSS to each of its blocks. When I point the Route in CF to the site, the images resize and are served as expected. However, the Worker re-writes the `>` character within the inline CSS to `&gt;`. Resulting in CSS borking. 

The image below displays the resulting CSS - on the left is without the Worker, on the right is with the Worker. Are you able to provide any support with adjusting this? 

![Screenshot 2023-04-19 at 18 15 18](https://user-images.githubusercontent.com/13104185/233154421-14f8f689-c59b-48a2-8775-dc9f0d2701ca.png)

**Comment by IntricateGrapeVine** [comment]
+1 on this issue.
I am using GeneratePress, which is adding inlineCSS to control some of the styling. 

My short term solution is to comment out the call of the StyleTagRewriter class in line 414 (this disables all rewriting of <style> tags though)
`//.on('style', new StyleTagRewriter())`

**Comment by Mecanik** [comment]
Hi both, I will update the script soon. I had some delays with work etc.

**Comment by Mecanik** [comment]
Hi,

Sorry for the delay, this has been fixed in the latest version. It seems the HTMLRewriter was understanding the content differently.

Regards
