### ISSUE TITLE
Icons gone missing

### ISSUE THREAD

**Issue by philipp089** [Mecanik/cloudflare-image-resizing-worker#9]
Hi, 

first of all, thank you for your effort and the worker configuration. After copying it and routing it, the icons are gone missing and i really do not know how to fix this.

<img width="335" alt="image" src="https://github.com/Mecanik/cloudflare-image-resizing-worker/assets/66092908/45e0e09d-127a-4748-8a81-5c6211780fc1">

Any help is much appreciated.

Cheers,
Philipp

**Comment by Mecanik** [comment]
Hi,

Most likely the CSS rewrite is breaking it. Please comment out the CSS rewrite part from here: https://github.com/Mecanik/cloudflare-image-resizing-worker/blob/322adcad43725fb72effe40d7131a40d8d626d09/wordpress-worker.js#L424

Thanks

**Comment by philipp089** [comment]
Hi, 

sorry to ask that but totally new to me, until which line do i comment it out? Line 457? Thanks in advance.

Cheers, 
Philipp

**Comment by Mecanik** [comment]
> Hi,
> 
> sorry to ask that but totally new to me, until which line do i comment it out? Line 457? Thanks in advance.
> 
> Cheers, Philipp

From 424 to 458 - the brackets where CSS is rewritten. There is a also a comment...

**Comment by Mecanik** [comment]
Hi,

In the latest version, a major improvement has been done in rewriting CSS.

Please try it, and if you still have problems open another issue.

Regards
